### ISSUE TITLE
在ubuntu上无法抓取密码

### ISSUE THREAD

**Issue by QiwanKing** [9bie/sshdHooker#2]
是不是clone下来的代码 要做适配性修改，直接运行代码 在/tmp下没有生成密码文件，但是ssh服务可以正常使用

![IMAGE 2022-07-28 17:28:27](https://user-images.githubusercontent.com/43790685/181472259-9c6d58a8-912a-4043-bd85-91a4b29bf685.jpg)

**Comment by 9bie** [comment]
你好，能提供下`uname -a`吗？我去本地测试一波

**Comment by helloyw** [comment]
我使用的是ubuntu22.04,/tmp目录下并没有生成文件
`Linux ubuntu 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
![image](https://user-images.githubusercontent.com/32027872/186337326-4331eebc-b340-4e4f-969d-a738c332fa9c.png)

**Comment by 9bie** [comment]
虽然晚了一些，但是已修复。并且做成了一键的了
