### ISSUE TITLE
aarch64编译失败

### ISSUE THREAD

**Issue by shadow1ng** [9bie/sshdHooker#3]
uname -a
Linux ecs-2817 4.18.0-147.5.1.el8_1.aarch64 #1 SMP Tue Feb 4 23:44:08 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
![image](https://user-images.githubusercontent.com/39651966/187429139-d3ed8ab1-f486-4c29-960f-dda893143718.png)

**Comment by 9bie** [comment]
暂时还只支持amd64,其他架构的还在写

**Comment by 9bie** [comment]
已aarch64架构
