### ISSUE TITLE
无法生成/tmp/set_data.txt记录文件

### ISSUE THREAD

**Issue by OFalwl** [9bie/sshdHooker#4]
测试系统：Linux ubuntu 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by OFalwl** [comment]
测试系统centos7成功记录
Linux 192.168.1.10.lightspeed.brhmal.sbcglobal.net 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by OFalwl** [comment]
测试系统centos7成功记录
Linux 3.10.0-1160.59.1.el7.x86_64 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 9bie** [comment]
已经修复
