### ISSUE TITLE
注入sshd后出现很多僵尸进程

### ISSUE THREAD

**Issue by accgitno** [9bie/sshdHooker#5]
如果服务器在外网被一直爆破 会一直出现sshd 僵尸进程无法释放的问题，导致服务器ps -aux 出现几千个sshd的进程

**Comment by 9bie** [comment]
已经修复，排查是由于ptrace接管后造成子进程ppid改变，原本宿主父进程无法处理子进程推出信号导致的

增加了手动GC以改善这个问题
